
const AI_CFG=window.AI_CONFIG||{}; AI_CFG.GROQ_MODEL='qwen/qwen3.8-27b';
function loadSavedApiKeys(){try{const x=JSON.parse(localStorage.getItem('vaultApiKeys')||'{}');if(x.groq)AI_CFG.GROQ_API_KEY=x.groq;return x}catch(e){return {}}}
function maskKey(k){return k?(k.slice(0,5)+'••••••'+k.slice(-4)):''}
function refreshApiKeyUI(){const q=AI_CFG.GROQ_API_KEY||'',qi=$('groqKeyInput'),st=$('apiKeyStatus');if(qi)qi.value=q;if(st)st.textContent=q?`Saved: Groq ✓ ${maskKey(q)}`:'Groq key is not loaded.'}
function saveApiKeys(){const q=$('groqKeyInput').value.trim();AI_CFG.GROQ_API_KEY=q;localStorage.setItem('vaultApiKeys',JSON.stringify({groq:q}));refreshApiKeyUI();toast('Groq API key saved on this device')}
function clearApiKeys(){AI_CFG.GROQ_API_KEY='';localStorage.removeItem('vaultApiKeys');refreshApiKeyUI();toast('Groq API key cleared')}
loadSavedApiKeys();
function closeAiMenu(){$('aiToolsPanel').classList.remove('open')}
$('aiAnalysisBtn').onclick=()=>openAnalysisPage();
$('aiMenuBtn').onclick=e=>{e.stopPropagation();$('aiToolsPanel').classList.toggle('open')};
document.addEventListener('click',e=>{if(!$('aiToolsPanel').contains(e.target)&&!$('aiMenuBtn').contains(e.target))closeAiMenu()});
function hideViews(){['homeView','detailView','analysisView','futureView','moneyView'].forEach(id=>{const e=$(id);if(!e)return;if(id==='homeView')e.style.display='none';else e.classList.remove('show')})}
function openAnalysisPage(){hideViews();$('analysisView').classList.add('show');scrollTo({top:0,behavior:'smooth'});requestNotificationPermissionOnce()}
function openFuturePage(){hideViews();$('futureView').classList.add('show');scrollTo({top:0,behavior:'smooth'});requestNotificationPermissionOnce()}
function openMoneyPage(){hideViews();$('moneyView').classList.add('show');scrollTo({top:0,behavior:'smooth'})}
function showHome(){hideViews();$('homeView').style.display='block';scrollTo({top:0,behavior:'smooth'})}
function previewImageInput(input,id){const f=input.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>$(id).innerHTML=`<img src="${r.result}" alt="Chart preview">`;r.readAsDataURL(f)}
$('analysisImage').addEventListener('change',()=>previewImageInput($('analysisImage'),'analysisPreview'));
$('futureImage').addEventListener('change',()=>previewImageInput($('futureImage'),'futurePreview'));
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function cleanJsonText(t){let s=String(t||'').trim().replace(/^```(?:json)?/i,'').replace(/```$/,'').trim();const a=s.indexOf('{'),b=s.lastIndexOf('}');return a>=0&&b>a?s.slice(a,b+1):s}
const SIGNAL_SCHEMA='Return ONLY valid JSON: {"market":"detected market/pair or UNKNOWN","signal":"UP|DOWN|STOP","confidence":0-100,"timeframe":"string","reason":"short reason","risk":"LOW|MEDIUM|HIGH"}. Detect visible market/pair. Never invent it. Use UNKNOWN if unreadable.';
function buildPrompt(m,tf,c,mode,marketData){return `You are a technical-chart analysis assistant. Analyze the Quotex screenshot. Automatically detect the market/pair from visible text/header/watermark. Do not ask the user for market/pair. Candle timeframe: ${tf}. Mode: ${mode}. Extra context: ${c||'none'}. ${marketData||''} Inspect trend, structure, momentum, support/resistance, candle bodies/wicks and current candle. Predict next candle direction only when evidence is sufficiently strong. Use STOP if chart is unreadable or evidence is weak. ${SIGNAL_SCHEMA}`}
function dataUrlFromFile(f){return new Promise((res,rej)=>{if(!f)return rej(Error('No image selected'));const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(Error('Could not read image'));r.readAsDataURL(f)})}
async function prepareChartImage(f){const raw=await dataUrlFromFile(f);return await new Promise(resolve=>{const im=new Image();im.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(im.naturalWidth,im.naturalHeight));const w=Math.max(1,Math.round(im.naturalWidth*scale)),h=Math.max(1,Math.round(im.naturalHeight*scale));const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);resolve(c.toDataURL('image/jpeg',.84))};im.onerror=()=>resolve(raw);im.src=raw})}
function keyMissing(v){return !v||String(v).trim()===''||String(v).includes('PASTE_')}
function apiErrorText(p,s,t){let m='';try{const j=JSON.parse(t||'{}');m=j.error?.message||j.message||''}catch{}return p+' '+s+(m?' • '+m:'')}
function imageParts(img){const m=(String(img).match(/^data:(image\/[^;]+);base64,/)||[])[1]||'image/jpeg';return {mime_type:m,data:String(img).split(',')[1]||''}}
async function callGroq(img,prompt){if(keyMissing(AI_CFG.GROQ_API_KEY))throw Error('Groq key not configured');const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+AI_CFG.GROQ_API_KEY},body:JSON.stringify({model:AI_CFG.GROQ_MODEL||'qwen/qwen3.6-27b',messages:[{role:'user',content:[{type:'text',text:prompt},{type:'image_url',image_url:{url:img}}]}],temperature:.4,max_completion_tokens:1000,reasoning_format:'hidden',response_format:{type:'json_object'}})});if(!r.ok)throw Error(apiErrorText('Groq',r.status,await r.text()));const j=await r.json(),t=j.choices?.[0]?.message?.content||'';if(!t)throw Error('Groq returned empty response');return t}
async function callGemini(){throw Error('Gemini disabled — Groq only mode.')}
function parseSignal(raw,name){try{const j=JSON.parse(cleanJsonText(raw));return{name,market:j.market||'UNKNOWN',signal:['UP','DOWN','STOP'].includes(String(j.signal).toUpperCase())?String(j.signal).toUpperCase():'STOP',confidence:Math.max(0,Math.min(100,Number(j.confidence)||0)),reason:j.reason||'No reason returned.',risk:j.risk||'HIGH',timeframe:j.timeframe||''}}catch{return{name,market:'UNKNOWN',signal:'STOP',confidence:0,reason:'AI returned unreadable JSON.',risk:'HIGH',timeframe:''}}}
function signalClass(s){return s==='UP'?'signal-up':s==='DOWN'?'signal-down':'signal-stop'}
function chooseBest(results){if(!results.length)throw Error('Both AI services failed. Add valid Gemini/Groq API keys and try again.');const usable=results.filter(r=>r.signal!=='STOP');if(usable.length===1)return {...usable[0],source:'FALLBACK: '+usable[0].name};if(usable.length>1){const same=usable.every(r=>r.signal===usable[0].signal);if(same)return {...usable.sort((a,b)=>b.confidence-a.confidence)[0],confidence:Math.round(usable.reduce((s,r)=>s+r.confidence,0)/usable.length),source:'GROQ ONLY AGREED'};return {...usable.sort((a,b)=>b.confidence-a.confidence)[0],source:'HIGHER-CONFIDENCE AI'}}return {...results.sort((a,b)=>b.confidence-a.confidence)[0],source:'AI RESULT'}}

function renderDualAI(r,all){return `<div class="analysis-card consensus-card"><div><div class="eyebrow">FINAL AI SIGNAL</div><div class="signal-badge ${signalClass(r.signal)}">${r.signal}</div><div class="confidence">Confidence estimate: ${r.confidence}% • ${esc(r.source)}</div><div class="analysis-note"><b>DETECTED MARKET:</b> ${esc(r.market)}</div></div><div style="font-size:34px">${r.signal==='UP'?'🟢':r.signal==='DOWN'?'🔴':'🛑'}</div></div><div class="analysis-card"><div class="section-head"><h2>AI STATUS</h2><span>GROQ ONLY</span></div>${all.map(x=>`<div class="model-card"><div class="model-signal ${signalClass(x.signal)}">${x.name}: ${x.signal} ${x.confidence}%</div><div class="model-reason">${esc(x.reason)}</div><div class="analysis-note">Risk: ${esc(x.risk)} • ${esc(x.timeframe||'current candle')}</div></div>`).join('')}</div>`}
async function runDualAI(img,setL){
  const prompt=buildPrompt('',$('analysisTimeframe').value,$('analysisContext').value.trim(),'next-candle','Use screenshot only; no external market data.');
  setL('GROQ QWEN ANALYZING…');
  const raw=await callGroq(img,prompt);
  const result=parseSignal(raw,'GROQ');
  $('analysisMarketAuto').textContent='DETECTED: '+result.market;
  return {final:result,all:[result]};
}
$('runAnalysisBtn').onclick=async()=>{const file=$('analysisImage').files?.[0];if(!file)return toast('Upload a Quotex chart screenshot first');$('aiLoader').classList.add('show');$('analysisResults').classList.remove('show');try{const img=await prepareChartImage(file),out=await Promise.race([runDualAI(img,t=>$('loaderText').textContent=t),wait(30000).then(()=>{throw Error('Analysis timed out. Try again.')})]);$('analysisResults').innerHTML=renderDualAI(out.final,out.all);$('analysisResults').classList.add('show')}catch(e){$('analysisResults').innerHTML=`<div class="analysis-card"><div class="signal-badge signal-stop">STOP</div><div class="reason-box">${esc(e.message||'Analysis failed.')}</div></div>`;$('analysisResults').classList.add('show')}finally{$('aiLoader').classList.remove('show')}};

function buildFuturePrompt(m,tf,c,marketData){return `Analyze this trading chart screenshot as an educational scenario. Market: ${m||'unknown'}. Candle: ${tf} minute(s). Generate ${c} possible scenarios within the next 30 minutes. Market-data context: ${marketData||'not available; do not invent it.'}. Use visible chart evidence only. Return ONLY JSON: {"market":"detected market/pair or UNKNOWN","signals":[{"afterMinutes":number,"signal":"UP|DOWN|STOP","confidence":number,"reason":"short reason"}]}. No guaranteed predictions.`}
function renderFuture(j){return `<div class="analysis-card"><div class="section-head"><h2>30-MINUTE OUTLOOK</h2><span>AI SCENARIOS</span></div><div class="future-list">${j.signals.map(x=>`<div class="future-item"><div class="future-time">+${Number(x.afterMinutes)||0} MIN</div><div class="future-main"><b>Future candle scenario</b><span>${esc(x.reason||'No reason')}</span></div><div class="future-sig ${signalClass(String(x.signal||'STOP').toUpperCase())}">${String(x.signal||'STOP').toUpperCase()}<br><small>${Number(x.confidence)||0}%</small></div></div>`).join('')}</div><div class="analysis-note">Scenario estimates only; live market data is optional and may not match Quotex OTC pricing.</div></div>`}
async function futureDual(img,p,setL){setL('GROQ QWEN ANALYZING…');const raw=await callGroq(img,p);return {name:'GROQ',j:JSON.parse(cleanJsonText(raw))}})).catch(e=>({failed:true,name:'GEMINI',error:e.message})),callGroq(img,p).then(x=>({name:'GROQ',j:JSON.parse(cleanJsonText(x))})).catch(e=>({failed:true,name:'GROQ',error:e.message}))];const rs=await Promise.all(jobs),good=rs.filter(x=>!x.failed&&x.j?.signals?.length);if(!good.length)throw Error('Both AI services failed. Gemini: '+rs[0].error+' | Groq: '+rs[1].error);return good.sort((a,b)=>b.j.signals.length-a.j.signals.length)[0]}
$('runFutureBtn').onclick=async()=>{const file=$('futureImage').files?.[0];if(!file)return toast('Upload a chart screenshot first');$('futureLoader').classList.add('show');$('futureResults').classList.remove('show');try{const img=await prepareChartImage(file),p=buildFuturePrompt('',$('futureTimeframe').value,$('futureCount').value,''),out=await Promise.race([futureDual(img,p,t=>document.querySelector('#futureLoader .loader-text').textContent=t),wait(30000).then(()=>{throw Error('Analysis timed out. Try again.')})]);$('futureMarketAuto').textContent='DETECTED: '+(out.j.market||'UNKNOWN');$('futureResults').innerHTML=renderFuture(out.j)+`<div class="analysis-card"><div class="analysis-note"><b>AI:</b> ${out.name} • If the other AI failed, the working AI result is used automatically.</div></div>`;$('futureResults').classList.add('show')}catch(e){$('futureResults').innerHTML=`<div class="analysis-card"><div class="signal-badge signal-stop">STOP</div><div class="reason-box">${esc(e.message||'Future analysis failed.')}</div></div>`;$('futureResults').classList.add('show')}finally{$('futureLoader').classList.remove('show')}};
const DAYS=[['1','DAY 1'],['2','DAY 2'],['3','DAY 3'],['4','DAY 4'],['5','DAY 5'],['6','DAY 6'],['7','DAY 7'],['14','14 DAYS'],['30','30 DAYS']];let selectedDays=['1','2','3'];$('moneyDays').innerHTML=DAYS.map(([v,t])=>`<button class="day-chip ${selectedDays.includes(v)?'active':''}" data-day="${v}">${t}</button>`).join('');document.querySelectorAll('.day-chip').forEach(b=>b.onclick=()=>{const v=b.dataset.day;if(selectedDays.includes(v))selectedDays=selectedDays.filter(x=>x!==v);else selectedDays.push(v);b.classList.toggle('active')});$('generateMoneyBtn').onclick=()=>{const bal=Number($('mmBalance').value),risk=Number($('mmRisk').value);if(!bal||bal<=0)return toast('Enter a valid balance');if(!selectedDays.length)return toast('Select at least one day');const daily=bal*risk/100,rows=selectedDays.sort((a,b)=>Number(a)-Number(b)).map(d=>{const n=Number(d),base=bal*Math.pow(1-risk/100,n-1),loss=base*risk/100;return `<div class="future-item"><div class="future-time">DAY ${n}</div><div class="future-main"><b>Max planned risk: $${loss.toFixed(2)}</b><span>Suggested daily stop after reaching the risk limit.</span></div><div class="future-sig signal-stop">🛡️</div></div>`}).join('');$('moneyResult').innerHTML=`<div class="eyebrow">YOUR PLAN</div><h2 style="font-family:Orbitron;margin:8px 0">💎 Risk-first management</h2><div class="money-result">Balance: <strong>$${bal.toFixed(2)}</strong><br>Selected risk: <strong>${risk}% per day</strong><br>Starting daily risk cap: <strong>$${daily.toFixed(2)}</strong></div><div class="future-list" style="margin-top:12px">${rows}</div><div class="analysis-note">Risk-control template only. It is not a profit guarantee and should not be treated as personalized financial advice.</div>`};
